### ISSUE TITLE
kayitoEditor 

### ISSUE THREAD

**Issue by yao123ge** [nicomuratona/MuEmu-0.97k-kayito#10]
The kayitoEditor tool still uses Chinese encoding, and changing it to Chinese results in an error " readscript there is error in file '.\data\item.txt' in line XXX"

**Comment by nicomuratona** [comment]
I did everything thinking about only in GMO languages (Spanish, English and Portuguese).
I'm not interested in giving support to another languages but i can help on searching alternatives.
