### ISSUE TITLE
arrows

### ISSUE THREAD

**Issue by yao123ge** [nicomuratona/MuEmu-0.97k-kayito#12]
Does a later version consider updating the elf with infinite arrows?

**Comment by nicomuratona** [comment]
This main doesn't have Infinite Arrows because doesn't exist the Marlon quest neither the buff infinity arrows.
I don't know if i will add it in next updates.

**Comment by yao123ge** [comment]
Is it possible to expand or something like that so that the arrows don't consume?

**Comment by nicomuratona** [comment]
You can check the source code of the GameServer, search for the function called `bool CAttack::DecreaseArrow(LPOBJ lpObj)` in Attack.cpp and modify it to avoid decreasing arrows if you want.
