### ISSUE TITLE
itemdrop

### ISSUE THREAD

**Issue by yao123ge** [nicomuratona/MuEmu-0.97k-kayito#13]
itemdrop,I set MapNum =6,But if other maps have monsters in mapnum6,You can also drop the corresponding item,Is MapNum here referring to all monsters on this map? Instead of saying that only a specific map drops?

**Comment by nicomuratona** [comment]
In Item.txt is specified the "Drop" column that means EVERY map will have a rate to drop that item (Depends on the monster level too). If you want an item just to be droped in a specific map, you should set Drop column in Item.txt to 0 and configure the ItemDrop.txt for that item manually (like the MapNumber, DropRate, ItemOptions, etc). Another way of controlling the drop rate of an item is setting Drop column to 0 and add it to ItemDrop with `MapNumber = *`. That way you can specify all the drop configs for every map for that specific item.
