### ISSUE TITLE
experience 

### ISSUE THREAD

**Issue by yao123ge** [nicomuratona/MuEmu-0.97k-kayito#15]
24 new version,Is it because the level has become 1000,I set the maximum level to 400,But the experience bar is obviously faster than before the upgrade.,The same experience before,It took a day to upgrade a level.,Now it doesn't take long to upgrade a level.

**Comment by nicomuratona** [comment]
If you change the maximum level, you also have to adapt the experience equation according to the level you choose. It is currently functional for level 1000 by default but if you want to lower the maximum level, you will have to modify the experience equation.
You can find it in the GameServer source code inside of User.cpp -> gObjSetExperienceTable
In the Main.dll source code inside of PrintPlayer -> RenderExperience

**Comment by yao123ge** [comment]
I mean, I changed the MaxCharacterLevel of the Common.dat file from 1000 to 400, and the player progressed a lot faster on the experience bar when killing the same monster than in the previous version

**Comment by yao123ge** [comment]
I found a place to modify the experience points, thanks
