### ISSUE TITLE
Main.exe isn't running 

### ISSUE THREAD

**Issue by YuvalGal2** [nicomuratona/MuEmu-0.97k-kayito#2]
machine type : windows 11 Home 
machine - 32GB ram, i7 7700hq

when trying to run main.exe, nothing happens.

can you please provide a solution for this issue? (and matching client + editing tools for main.exe)

**Comment by YuvalGal2** [comment]
follow this tutorial instead of just using the main.exe in the client folder https://www.youtube.com/watch?v=WR45J4SjSHA

**Comment by nicomuratona** [comment]
I've made an official tutorial for people who don't know how to start muemu based files like you.

Here you have: https://youtu.be/P_CUCu7a_Dw

In the repository you have everything you need to configure the server side and client side, even tools to edit the database.

Have fun !
