### ISSUE TITLE
BUFF

### ISSUE THREAD

**Issue by yao123ge** [nicomuratona/MuEmu-0.97k-kayito#26]
After using the buff, the archer and mage will not disappear after 60 seconds, and will only lose the buff when they die or go offline

**Comment by lineagedr** [comment]
Hmm I used greater defense on my archer and after 60 it was removed. This was called: https://github.com/nicomuratona/MuEmu-0.97k-kayito/blob/master/Source/MuServer/GameServer/EffectManager.cpp#L170
