### ISSUE TITLE
main.dll

### ISSUE THREAD

**Issue by yao123ge** [nicomuratona/MuEmu-0.97k-kayito#27]
The new version of main.dll will crash in some systems (win7 win10), which was normal when it was 24UP before, and only happens after upgrading to 25UP

**Comment by lineagedr** [comment]
What's 24UP, 25UP?

**Comment by yao123ge** [comment]
> What's 24UP, 25UP?

Update 24、 update25，
The version of update23 cannot use Chinese, and the later version of 24 solved this problem, and then I followed the update of the version of update25, and some friends would crash when logging in to the game, but the previous version did not have a flashback

**Comment by yao123ge** [comment]
> What's 24UP, 25UP?

Update 24、 update25，
The version of update23 cannot use Chinese, and the later version of 24 solved this problem, and then I followed the update of the version of update25, and some friends would crash when logging in to the game, but the previous version did not have a flashback
