### ISSUE TITLE
how choose server2

### ISSUE THREAD

**Issue by yao123ge** [nicomuratona/MuEmu-0.97k-kayito#30]
![长图_1733318284866](https://github.com/user-attachments/assets/1ce08fc2-b9f9-413c-8bec-7ae9ee5bb72d)

**Comment by nicomuratona** [comment]
The servers are listed 20 per box using ServerCode.

ServerCode 0~19 will be at Server 1
ServerCode 20~39 will be at Server 2
ServerCode 40~59 will be at Server 3
Etc...
