### ISSUE TITLE
Uma ajuda

### ISSUE THREAD

**Issue by joascr7** [nicomuratona/MuEmu-0.97k-kayito#32]
Olá kayito, tudo bem contigo? Gostaria de saber se á possibilidade de você adicionar CustomJewel no servidor, sou novo nessa área, não conheço ninguém com tamanha perfeição para mexer no seu código a não ser vc mesmo.

como a versão 97k ou 97d  é voltada para o pvp, seria bacana tambem colocar um comando  /evento onde o mesmo iria mandar uma mensagem de evento iniciando em alguns segundo...

exemplo: /evento SOBREVIVENCIA 6 60 160 60 (60segundos)  player: /queroir

outra sugestão tbm  que nunca vi em 97, chaos mix até +15 ( com probabilidade do item falhar e desce nivel ao invez de perde o item )

Erro que encontrei mas n prejudica o servidor: martelinho de reparar arma, n se movimenta só faz barulho até mesmo se o item não tiver quebrado.

**Comment by joascr7** [comment]
Salve kayito, depois dessa att 26, o ping ficou cravado em zero no cliente.

**Comment by nicomuratona** [comment]
Olá, bom. No momento não pretendo adicionar novos sistemas além daqueles que acabei de adicionar na Atualização 26. Você tem o código-fonte disponível e qualquer programador pode fazer o que você propõe, pois é algo simples de fazer.
Em relação ao ping, verifique se sua hospedagem permite fazer ping corretamente e não está bloqueada para fazê-lo. O sistema foi verificado em hospedagem diferente e aquelas que falharam tiveram que ser configuradas para permitir ping.
