### ISSUE TITLE
How to support the+15 project?

### ISSUE THREAD

**Issue by daotaam** [nicomuratona/MuEmu-0.97k-kayito#33]
How to support the+15 project?

**Comment by yao123ge** [comment]
You can put it in the shop for sale or customize the drop

**Comment by nicomuratona** [comment]
You have to add the support in the source of the gameserver and the main.dll.
Check every place where the maximum level is 11 and add cases until you reach +15 as you want.
The project is adaptable to support +15 but you'll have to add each case by yourself in the gameserver and search the offsets in the main
