### ISSUE TITLE
Does it support Unicode characters？such as Chinese

### ISSUE THREAD

**Issue by 8923052** [nicomuratona/MuEmu-0.97k-kayito#4]
Does it support Unicode characters？such as Chinese

I have tried to translate it into Chinese, and there is no problem with the item. The movelist and NPCName display garbled characters

**Comment by yao123ge** [comment]
PK bug, when PKlevel > 5, the character goes offline, and after re-online, kill a character again, and the previous PKlevel will change back to 4

**Comment by nicomuratona** [comment]
You have to change the Charset in the Config.ini to enable characters you want to use.
For example for chinese characters, use FontCharset=134

**Comment by 8923052** [comment]
OK, thanks.
