### ISSUE TITLE
EventItemBag Bug

### ISSUE THREAD

**Issue by jqcold5** [nicomuratona/MuEmu-0.97k-kayito#6]
```
4
//ItemIndex	ItemLevel	ItemGrade	LevelRate	SkillRate	LuckRate	OptionRate	ExcellentRate	Comment
03,010		0		0		*		*		*		*		22		//Dragon Spear
end
```
The preceding "ItemIndex" field of the advanced drop in the "EventItemBag" configuration file (03,010) doesn't get read correctly, while the subsequent item index value 010 gets read and overrides the type index value. At this point, the "ItemIndex" field value changes from (03,010) to (10,010), resulting in the actual dropped item from the chest being (10,010) instead of the intended (03,010). Of course, there might be an error in my configuration. Below is the complete configuration file:

```
//======================================
// NORMAL DROP
//======================================

0
//EventName		 DropZen	ItemDropRate	ItemDropCount	ItemDropType	Fireworks	
"Box of Kundun 1"	 1000	        100	        1		1		0
end

1
//Item	MinLvl	MaxLvl	Skill	Luck	Opt	Exce	Comment
//00,000	0	0	0	0	0	0	//Comment
end

//======================================
//ADVANCED DROP
//======================================

2
//Index	DropRate
0	10000
end

3
//Index	Section	SectionRate	MoneyAmount	OptionValue	DW	DK	FE	MG
0	4	10000		0		0		1	1	1	1
end

// ItemGrade works when ExcellentRate = 0
// LevelRate, SkillRate, LuckRate, OptionRate and ExcellentRate
// Uses ItemOptionRate Indexes
4
//ItemIndex	ItemLevel	ItemGrade	LevelRate	SkillRate	LuckRate	OptionRate	ExcellentRate	Comment
03,010		0		0		*		*		*		*		22		//Dragon Spear
end
```

**Comment by nicomuratona** [comment]
Fixed in commit https://github.com/nicomuratona/MuEmu-0.97k-kayito/commit/604077b4399a604e4ff9b066974987947c37f966

**Comment by jqcold5** [comment]
After testing, this bug has been fixed in the latest update. Thank you to the author for their hard work.
