### ISSUE TITLE
ping?

### ISSUE THREAD

**Issue by yao123ge** [nicomuratona/MuEmu-0.97k-kayito#7]
I install the service locally and run the client, why does the ping still go up to 40-60 ms? Shouldn't it be less than 1 ms?

**Comment by nicomuratona** [comment]
I really don't know because the code simply sends a packet with the current time and upon receiving the response, calculates the time difference between the packet sent and the packet received. I can't think of where that delay comes from.

**Comment by yao123ge** [comment]
Will this delay be caused by passing through the server, and if it is executed directly through the IP address of the client, will this not happen?
