### ISSUE TITLE
IsEncodingAnsi

### ISSUE THREAD

**Issue by yao123ge** [nicomuratona/MuEmu-0.97k-kayito#8]
I found that version 23 has an encoding conversion IsEncodingAnsi in the MemScript.cpp file, I don't know what the reason is, when I use the Chinese in the ServerName in the ServerList.dat file, there will be garbled characters, I tried to change the file encoding from utf-8 to ansi, it still shows garbled characters, but the 22 version does not have this case, because it does not have IsEncodingAnsi.

**Comment by nicomuratona** [comment]
Yes, i corrected that but not uploaded the update yet. Next commit will have the correction of that

**Comment by yao123ge** [comment]
That would be fantastic
